icss:
  db:
    name: icss_db
    username: root
    host: 127.0.0.1
    pw: 1234
  cloud:
    addr: 127.0.0.1:8848
  redis:
    host: 127.0.0.1
    port: 6379
    pw: 123456
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: icss
    pw: 1234